#!/bin/bash

echo "Setting up server"

# First remove cdrom as a source
# Check the main sources.list file for CD-ROM entries
sed -i '/^deb cdrom:/d' /etc/apt/sources.list

# Check additional sources.list files in the sources.list.d directory
find /etc/apt/sources.list.d -type f -name "*.list" -exec sed -i '/^deb cdrom:/d' {} +

# Update APT
apt update
apt upgrade

echo "Making USB Tethering more reliable"
apt install network-manager dialog

# remove phone interface so no longer handled by ifupdown
rm /etc/network/interfaces.d/phone

dialog --msgbox "Please disconnect and reconnect your phone via USB then enable Tethering:\n\nSettings -> Connections -> Mobile Hotspot and Tethering -> Enable USB Tethering\n\nPress Enter when finished" 20 85

apt install sudo dialog
usermod -a -G sudo user

# Get packages
curl -s https://packagecloud.io/install/repositories/responsivetech/mapa-server/script.deb.sh | bash

apt update
apt upgrade

wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
apt install ./cloudflared-linux-amd64.deb
